name: The Next Episode Backend Auto CI Process Script

on:
  push:
    branches: [dev]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Disable host key checking
        run: |
          echo -e "Host *\n  StrictHostKeyChecking no\n  UserKnownHostsFile=/dev/null" > ~/.ssh/config

      - name: Execute remote SSH commands
        env:
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_IP: ${{ secrets.REMOTE_IP }}
        run: |
          ssh -i ~/.ssh/id_ed25519 $REMOTE_USER@$REMOTE_IP << 'EOF'
            cd /home/ubuntu/thenextepisode.backend
            git pull origin dev
            pm2 kill || true
            yarn install --force
            rm -rf build
            export NODE_OPTIONS="--max-old-space-size=4096"
            yarn build
            pm2 start build/src/main.js
          EOF
